# cloud:
#   gateway:
#      routes:
#        - id: Student-Service
#          uri: http://catalog-service:8810/
#          predicates:
#            - Path=/products/**
#            - Path=/admin/products