apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: catalog-service
        image: europe-central2-docker.pkg.dev/inspiring-tower-411321/pi/product-catalog-service:1.1.80
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 1000m
        ports:
        - containerPort: 8810
    # spec:
    #   containers:
    #   - name: catalog-service
    #     image: europe-central2-docker.pkg.dev/inspiring-tower-411321/pi/product-catalog-service:latest
    #     ports:
    #     - containerPort: 8810

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - protocol: TCP
    port: 8810
    targetPort: 8810