apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: pvc-374df8c3-ca5c-4c37-bc0b-a3c57a96e7f2
    fsType: ext4