apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: pvc-e5f41b7c-abfb-4cca-88f9-a0bf2d260a38
    fsType: ext4