apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: pvc-a3f9b8e1-a735-4122-ab85-adfb7c00c482
    fsType: ext4