apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: order-service
        image: europe-central2-docker.pkg.dev/inspiring-tower-411321/projet/order-service:1.1.26
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8813

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 8813
    targetPort: 8813