name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# europe-central2-docker.pkg.dev/project-762066161/nestleshop
env:
  PROJECT_ID: project-762066161 # TODO: update Google Cloud project id
  GAR_LOCATION: europe-central2 # TODO: update Artifact Registry location
  SERVICE: nestleshop # TODO: update Cloud Run service name
  REGION: europe-central2 # TODO: update Cloud Run service region
  CLUSTER_NAME: nestleshop

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: 'access_token'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build Container
        run: docker-compose build

      - name: Push Container
        run: docker-compose push 

      - name: get credentials
        id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.CLUSTER_NAME }}'
          location: '${{ env.GAR_LOCATION }}'
          credentials: '${{ steps.auth.outputs.access_token }}'

      - name: setup GKE cluster
        id: 'setup-cluster'
        run: kubectl apply -f k8s/.


      